%% gaussianSimilarity
% Evaluation of a data set to see if it is close to a 1D Gaussian distribution
%% Syntax
% * 		similarity=gaussianSimilarity(x, binNum)
% * 		similarity=gaussianSimilarity(x, binNum, plotOpt)
%% Description
% 		similarity=gaussianSimilarity(x, binNum) return the similarity of the dataset being generated by a 1D Gaussian PDF
%% Example
%%
%
dataNum=1000;
x=randn(dataNum, 1);
subplot(2,1,1);
gaussianSimilarity(x, 20, 1);
x=rand(dataNum, 1);
subplot(2,1,2);
gaussianSimilarity(x, 20, 1);
